# API Configuration
DEFAULT_PORT = 8080

# GitHub API Limits
MAX_PR_FILES = 10
MAX_PATCH_SIZE = 500
MAX_FILE_CHANGES_DISPLAY = 500
MAX_ISSUES_TO_PRIORITIZE = 15
ISSUES_PER_PAGE = 30

# OpenAI Configuration
SUMMARY_MAX_TOKENS = 300
ISSUE_MAX_TOKENS = 300
PRIORITIZE_MAX_TOKENS = 300
EXTRACT_DETAILS_MAX_TOKENS = 400
CHAT_MAX_TOKENS = 5000

# Cache
CACHE_FILE = '.summary_cache.json'
